name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::303972439808:role/github-actions-MatheusC96"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "matheuscarraro-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "matheuscarraro-sa-east-1-terraform-lock"
